Repository AY2324S2-CS2103T-T09-3/tp, pull requests merged in 2024-04, with the labels that each got.

#106 Add LogFind command
  docs/UserGuide.md
  src/main/java/scrolls/elder/logic/commands/AddCommand.java
  src/main/java/scrolls/elder/logic/commands/ClearCommand.java
  src/main/java/scrolls/elder/logic/commands/DeleteCommand.java
  src/main/java/scrolls/elder/logic/commands/EditCommand.java
  src/main/java/scrolls/elder/logic/commands/ListCommand.java
  src/main/java/scrolls/elder/logic/commands/LogAddCommand.java
  src/main/java/scrolls/elder/logic/commands/LogEditCommand.java
  src/main/java/scrolls/elder/logic/commands/LogFindCommand.java
  src/main/java/scrolls/elder/logic/commands/PairCommand.java
  src/main/java/scrolls/elder/logic/commands/RedoCommand.java
  src/main/java/scrolls/elder/logic/commands/UndoCommand.java
  src/main/java/scrolls/elder/logic/commands/UnpairCommand.java
  src/main/java/scrolls/elder/logic/parser/AddressBookParser.java
  src/main/java/scrolls/elder/logic/parser/LogFindCommandParser.java
  src/main/java/scrolls/elder/model/LogStore.java
  src/main/java/scrolls/elder/model/Model.java
  src/main/java/scrolls/elder/model/ReadOnlyLogStore.java
  src/main/java/scrolls/elder/storage/JsonSerializableDatastore.java
  src/test/java/scrolls/elder/logic/commands/LogAddCommandTest.java
  src/test/java/scrolls/elder/logic/commands/LogFindCommandTest.java
  src/test/java/scrolls/elder/logic/parser/LogFindCommandParserTest.java
Labels: priority.High

#117 Add testcases for Log commands and parsers
  src/test/java/scrolls/elder/logic/commands/EditLogDescriptorTest.java
  src/test/java/scrolls/elder/logic/commands/LogEditCommandTest.java
  src/test/java/scrolls/elder/logic/parser/LogAddCommandParserTest.java
  src/test/java/scrolls/elder/logic/parser/LogEditCommandParserTest.java
  src/test/java/scrolls/elder/testutil/EditLogDescriptorBuilder.java
Labels: priority.Medium, type.Task

#121 Fix check for duration to raise exception for value of 0
  src/main/java/scrolls/elder/logic/commands/LogAddCommand.java
  src/main/java/scrolls/elder/logic/commands/LogEditCommand.java
  src/test/java/scrolls/elder/logic/parser/LogAddCommandParserTest.java
  src/test/java/scrolls/elder/logic/parser/LogEditCommandParserTest.java
Labels: type.Task

#184 Update DG to include feature implementations
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DatastoreClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogAddSequenceDiagram-Logic.puml
  docs/diagrams/LogAddSequenceDiagram2.puml
  docs/diagrams/LogDeleteSequenceDiagram-Logic.puml
  docs/diagrams/LogDeleteSequenceDiagram2.puml
  docs/diagrams/LogEditSequenceDiagram-Logic.puml
  docs/diagrams/LogEditSequenceDiagram2.puml
  docs/diagrams/LogFindSequenceDiagram-Logic.puml
  docs/diagrams/LogFindSequenceDiagram2.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PairSequenceDiagram-Logic.puml
  docs/diagrams/PairSequenceDiagram2.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DatastoreClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogAddSequenceDiagram-Logic.png
  docs/images/LogAddSequenceDiagram2.png
  docs/images/LogDeleteSequenceDiagram-Logic.png
  docs/images/LogDeleteSequenceDiagram2.png
  docs/images/LogEditSequenceDiagram-Logic.png
  docs/images/LogEditSequenceDiagram2.png
  docs/images/LogFindSequenceDiagram-Logic.png
  docs/images/LogFindSequenceDiagram2.png
  docs/images/ModelClassDiagram.png
  docs/images/PairSequenceDiagram-Logic.png
  docs/images/PairSequenceDiagram2.png
  src/main/java/scrolls/elder/model/util/SampleDataUtil.java
Labels: type.Task
