Repository AY2324S2-CS2103T-T09-3/tp, pull requests merged in 2024-03, with the labels that each got.

#4 Update project website
  docs/AboutUs.md
  docs/_sass/minima/_base.scss
  docs/images/gerteck.png
  docs/index.md
  docs/team/gerteck.md
Labels: documentation

#14 Update AboutUs and portfolio
  docs/AboutUs.md
  docs/images/sdevih.png
  docs/team/sdevih.md
Labels: documentation

#21 Update DeveloperGuide.md to include user stories and glossary
  docs/DeveloperGuide.md
Labels: documentation

#18 Update use cases section for add, delete and view list in Developer Guide
  docs/DeveloperGuide.md
  docs/team/johndoe.md
Labels: documentation

#22 Update use cases section for pair and tag in Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#61 Update delete command to use split list indexing
  src/main/java/scrolls/elder/logic/commands/DeleteCommand.java
  src/main/java/scrolls/elder/logic/parser/DeleteCommandParser.java
  src/test/java/scrolls/elder/logic/LogicManagerTest.java
  src/test/java/scrolls/elder/logic/commands/DeleteCommandTest.java
  src/test/java/scrolls/elder/logic/parser/AddressBookParserTest.java
  src/test/java/scrolls/elder/logic/parser/DeleteCommandParserTest.java
Labels: type.Task

#91 Improve test coverage for `model` package
  src/main/java/scrolls/elder/model/LogStore.java
  src/main/java/scrolls/elder/model/PersonStore.java
  src/main/java/scrolls/elder/model/log/Log.java
  src/test/java/scrolls/elder/model/DatastoreTest.java
  src/test/java/scrolls/elder/model/LogStoreTest.java
  src/test/java/scrolls/elder/model/ModelManagerTest.java
  src/test/java/scrolls/elder/model/PersonStoreTest.java
  src/test/java/scrolls/elder/model/UserPrefsTest.java
  src/test/java/scrolls/elder/model/log/LogTest.java
  src/test/java/scrolls/elder/model/tag/TagTest.java
  src/test/java/scrolls/elder/testutil/TypicalLogs.java
Labels: priority.Medium, type.Task

#96 Add Pair Flags and Tags in Find Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram2.puml
  docs/images/FindSequenceDiagram.png
  docs/images/FindSequenceDiagram2.png
  src/main/java/scrolls/elder/logic/commands/EditCommand.java
  src/main/java/scrolls/elder/logic/commands/FindCommand.java
  src/main/java/scrolls/elder/logic/parser/AddressBookParser.java
  src/main/java/scrolls/elder/logic/parser/FindCommandParser.java
  src/main/java/scrolls/elder/model/person/NameContainsKeywordsPredicate.java
  src/main/java/scrolls/elder/model/person/TagListContainsTagsPredicate.java
  src/test/data/JsonSerializableDatastoreTest/typicalPersonsDatastore.json
  src/test/java/scrolls/elder/logic/commands/EditCommandTest.java
  src/test/java/scrolls/elder/logic/commands/FindCommandTest.java
  src/test/java/scrolls/elder/logic/parser/AddressBookParserTest.java
  src/test/java/scrolls/elder/logic/parser/FindCommandParserTest.java
  src/test/java/scrolls/elder/model/person/TagListContainsTagsPredicateTest.java
  src/test/java/scrolls/elder/testutil/TypicalPersons.java
Labels: type.Story, type.Enhancement

#92 Add timeServed in Person and logic to update timeServed in LogAddCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  src/main/java/scrolls/elder/logic/commands/EditCommand.java
  src/main/java/scrolls/elder/logic/commands/LogAddCommand.java
  src/main/java/scrolls/elder/logic/commands/PairCommand.java
  src/main/java/scrolls/elder/logic/commands/UnpairCommand.java
  src/main/java/scrolls/elder/logic/parser/AddCommandParser.java
  src/main/java/scrolls/elder/model/person/Befriendee.java
  src/main/java/scrolls/elder/model/person/Person.java
  src/main/java/scrolls/elder/model/person/PersonFactory.java
  src/main/java/scrolls/elder/model/person/Volunteer.java
  src/main/java/scrolls/elder/model/util/SampleDataUtil.java
  src/main/java/scrolls/elder/storage/JsonAdaptedPerson.java
  src/main/java/scrolls/elder/ui/BefriendeeCard.java
  src/main/java/scrolls/elder/ui/PersonListPanel.java
  src/main/java/scrolls/elder/ui/VolunteerCard.java
  src/main/resources/view/BefriendeeListCard.fxml
  src/main/resources/view/VolunteerListCard.fxml
  src/test/data/JsonDatastoreStorageTest/invalidAndValidPersonDatastore.json
  src/test/data/JsonDatastoreStorageTest/invalidPersonDatastore.json
  src/test/data/JsonSerializableDatastoreTest/duplicatePersonDatastore.json
  src/test/data/JsonSerializableDatastoreTest/invalidPersonDatastore.json
  src/test/data/JsonSerializableDatastoreTest/typicalPersonsDatastore.json
  src/test/java/scrolls/elder/logic/commands/LogAddCommandTest.java
  src/test/java/scrolls/elder/model/person/PersonTest.java
  src/test/java/scrolls/elder/storage/JsonAdaptedPersonTest.java
  src/test/java/scrolls/elder/testutil/PersonBuilder.java
  src/test/java/scrolls/elder/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#104 Update LogEditCommand to edit timeServed when log is updated
  src/main/java/scrolls/elder/logic/commands/LogEditCommand.java
  src/test/java/scrolls/elder/logic/commands/LogAddCommandTest.java
  src/test/java/scrolls/elder/logic/commands/LogEditCommandTest.java
  src/test/java/scrolls/elder/logic/parser/LogAddCommandParserTest.java
  src/test/java/scrolls/elder/logic/parser/LogEditCommandParserTest.java
  src/test/java/scrolls/elder/testutil/EditLogDescriptorBuilder.java
Labels: priority.Medium, type.Task
